### ISSUE TITLE
✔[TODO] 게임 인터페이스 구상

### ISSUE THREAD

**Issue by Songein** [E-CyberGame/.github#10]
## Due date (expected)
06/17

## ToDo
- [x] 피그마 디자인

클라이언트 구현
- [x] 기본 UI 구현
- [ ] 파티창 대기 인원 UI 구현
- [ ] 레이드 선택창 슬라이더 UI 구현
